name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.23-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add make git

      - name: Run linters
        run: make lint

      - name: Run tests
        run: make test

      - name: Build API
        run: make build-api

      - name: Build Bot
        run: make build-bot
